[package]
name = "tenma"
version = "0.1.0"
edition = "2021"
rust-version = "1.78.0"

[dependencies]
bevy = "0.13.2"
bevy_mod_picking = { version = "0.18.2", features = ["backend_sprite"] }
derivative = "2.2.0"
rand = "0.8.5"

[[example]]
name="test"
path="src/test.rs"